#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [[ `git diff @ --name-only | grep -E "^(src|tests)/"` != "" ]]; then
  npm run build
  npm run ts:noWatch
  npm run lint:check -- --max-warnings 0
  npm t
fi
